name: Generate the full index archive for Bitnami Charts
on:
  push:
    branches:
      - full-index-archive
env:
  LAST_INDEX_URL: https://charts.bitnami.com/bitnami/index.yaml
  INDEXES_DIR: indexes
jobs:
  get-indexes:
    runs-on: ubuntu-latest
    name: Get Indexes
    steps:
      - id: checkout-full-index
        name: Checkout current full index.yaml
        uses: actions/checkout@v3
      - id: get-last-indexes
        name: Get indexes
        run: |
          mkdir $INDEXES_DIR
          curl $LAST_INDEX_URL -o ./$INDEXES_DIR/last_index.yaml
          cp bitnami/index.yaml ./$INDEXES_DIR/index.yaml
      - id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-indexes
          path: ./${{ env.INDEXES_DIR }}
          retention-days: 2
  merge-indexes:
    runs-on: ubuntu-latest
    name: Merge
    steps:
      - id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: source-indexes
      - id: ls
        name: ls
        run: ls
      - id: merge
        name: merge
        run: echo "merge"
         # yq eval-all '. as $item ireduce ({}; . *+ $item )' old_full_index.yaml reduced_index.yaml > intermediate_index.yaml
