name: Generate the full index archive for Bitnami Charts
on:
  push:
    branches:
      - full-index-archive
env:
  LAST_INDEX_URL: https://charts.bitnami.com/bitnami/index.yaml
  INDEXES_DIR: indexes
jobs:
  get-indexes:
    runs-on: ubuntu-latest
    name: Get Indexes
    steps:
      - id: checkout-full-index
        name: Checkout current full index.yaml
        uses: actions/checkout@v3
      - id: get-last-indexes
        name: Get indexes
        run: |
          mkdir $INDEXES_DIR
          curl $LAST_INDEX_URL -o ./$INDEXES_DIR/last_index.yaml
          cp bitnami/index.yaml ./$INDEXES_DIR/index.yaml
      - id: upload-artifact
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: indexes
          path: ./${{ env.INDEXES_DIR }}
          retention-days: 2
          if-no-files-found: error
  merge-indexes:
    runs-on: ubuntu-latest
    needs: get-indexes
    name: Merge
    steps:
      - id: download-artifact
        name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: indexes
      - id: merge
        name: Merge
        run: yq eval-all '. as $item ireduce ({}; . *+ $item )' index.yaml last_index.yaml > duplicates_index.yaml
      - id: upload-artifact
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: duplicates-index
          path: duplicates_index.yaml
          retention-days: 2
          if-no-files-found: error
  remove-dups:
    runs-on: ubuntu-latest
    needs: merge-indexes
    name: Remove Duplicates
    steps:
      - id: download-artifact
        name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: duplicates-index
      - id: Remove
        name: remove
        run: yq eval '.entries[] |= unique_by(.version)' duplicates_index.yaml > index.yaml
      - id: upload-artifact
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: full-index-archive
          path: index.yaml
          retention-days: 2
          if-no-files-found: error
