name: 'Generate the full index archive for Bitnami Charts'
on:
  push:
    branches:
      - 'full-index-archive'
env:
  LAST_INDEX_URL: https://charts.bitnami.com/bitnami/index.yaml
jobs:
  get-index:
    runs-on: ubuntu-latest
    name: "Get current Bitnami Charts index.yaml"
    steps:
      - id: download-index
        name: 'Download last Bitnami Charts index.yaml'
        run: |
          mkdir artifacts/
          curl $LAST_INDEX_URL -o ./artifacts/last_index.yaml
      - id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: last_index.yaml
          path: ./artifacts/
